name: Master workflow

on:
  push:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Verify dependencies
        run : go mod verify

      - name: Run go vet
        run : go vet ./...

      - name: Install staticcheck
        run : go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run : staticcheck ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run tests
        run : go test -race -vet=off ./...